config/routes.rb
Rails.application.routes.draw do
  resources :room_messages
  resources :rooms
  get "matches/matches"
  resources :candidates
  resources :companies
  devise_for :user_candidates, path: "candidate", controllers: { sessions: "user_candidates/sessions", registrations: "user_candidates/registrations" }
  devise_for :user_companies, path: "company", controllers: { sessions: "user_companies/sessions", registrations: "user_companies/registrations" }
  resources :jobs
  resources :matches

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "dashboard#index"

  get "/companies/:id/jobs" => "jobs#filter_job_company"

  get "/dashboard" => "dashboard#show"

  get "/candidate/createprofile" => "candidates#edit"
  get "/candidate/:id/edit" => "candidates#edit"

  get "/jobs/:id/matches" => "matches#companiesmatch"

  get "/jobs/:jobs_id/matches" => "matches#companiesmatch"

  get "/matches" => "matches#candidatesmatch"

  get 'users/:user_id/challenges' => 'challenges#user_challenges', as: :user_challenges

  match "*path", to: "dashboard#index", via: :all
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @home = true
    if user_company_signed_in? || user_candidate_signed_in?
      redirect_to "/dashboard"
    end
  end

  def show
    if user_company_signed_in?
      if current_user_company.company
        @company = Company.find(current_user_company.id)
        @pagy, @records = pagy(Job.where(company: @company))
        if @company.name == nil
          redirect_to edit_company_path(@company)
        end
      else
        @company = nil
      end
    elsif user_candidate_signed_in?
      @candidate = Candidate.find(current_user_candidate.id)
      matches_to_exclude = Match.where("job_like = false").pluck(:id)
      @pagy, @matches = pagy(Match.where(candidate: @candidate, candidate_like: true).where.not(id: matches_to_exclude))
    end
  end
end

app/views/dashboard/index.html.erb
<%= title "Linkdr | Where people hire software developers, but better" %>

<div class="container">
<div class="row">
<div class="col-sm-6 circle">
<%= image_tag('/workers-circle.jpg') %>
</div>

<div class="col-sm-6 text pt-5">
  <%= image_tag('/transparent-logo.png') %> <br><br>
Linkdr is where the people hire <strong>software developers</strong>. Like in real life, but better. <br>
  <div class="button-box submit">Join us today!</div>
</div>
</div>
</div>

<div class="overlay">
  <div class="signup-box box">
  <div class="text-right">
    <i class="close-box material-icons">close</i>
  </div>
    <div class="row">
      <div class="col-sm-6 text-center">
        <i class="material-icons header-icon">supervisor_account</i>
        <h2> Company</h2>
        <p>Hire Top Talents Fast and Cost-Efficiently</p>
        <ul class="text-left">
          <li><i class="material-icons">check</i> Top Quality Candidates </li>
          <li><i class="material-icons">check</i> Unlimited Jobs</li>
          <li><i class="material-icons">check</i> Unlimited Posting Duration</li>
        </ul>
        <%= link_to "/company/sign_up" do %>
          <div class="button-hire submit">Start Hiring</div>
        <% end %>
      </div>
      <div class="col-sm-6 text-center">
      <i class="material-icons header-icon">face</i>
        <h2>Candidate</h2>
        <p>Relevant Job Postings All Day Everyday</p>
        <ul class="text-left">
          <li><i class="material-icons">check</i> Relevant Job Postings</li>
          <li><i class="material-icons">check</i> Unlimited Application Duration</li>
        </ul>
        <%= link_to "/candidate/sign_up" do %>
          <div class="button-hire submit">Start Seeking</div>
        <% end %>
        </div>
    </div>
  </div>
</div>

<%# <p>if no cookies, show the sign up buttons / log in buttons otherwise, after sign in, will redirect to "/candidates/:id/dashboard" or "/companies/:id/dashboard"</p> %>

<script>
var button = document.querySelector('.button-box');
var closeBox = document.querySelector('.close-box');
var box = document.querySelector('.overlay');

button.addEventListener('click', () => {
  box.style.display = "block"
})

closeBox.addEventListener('click', () => {
    box.style.display = "none"
})
</script>

app/views/dashboard/show.html.erb
<%= title "Linkdr | Dashboard" %>

<div class="container company">
  <% if user_company_signed_in? %>
    <div class="container candidate">
      <h2>Hey, <span class="highlight"><%= @company.name %></span>! </h2>
      <br>
      <section class="candidate-info">
        <div class="row">
          <div class="col-sm-7 profile">
            <div class="row">
              <div class="col-6">
                <h3>Your Profile</h3>
              </div>
              <div class="col-6 text-right">
                <%= link_to edit_company_path(@company) do %>
                  <i class="material-icons">edit</i>
                <% end %>
              </div>
            </div>
            <div class="row">
              <div class="col-8">
                <strong>Company Name:</strong><br><%= @company.name %><br>
                <strong>Company Industry:</strong><br><%= @company.industry %><br>
                <strong>Company Size:</strong><br><%= @company.size %><br>
              </div>
              <div class="col-4 profile-pic">
                <% if current_user_company.company.avatar_url != nil %>
                  <%= image_tag current_user_company.company.avatar_url %>
                <% else %>
                  <%= image_tag current_user_company.gravatar_url %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="offset-sm-1 col-sm-4 stats pt-5">
            Your company profile has been viewed <strong><%= @company.views %></strong> times.
            <br>
            <br>
            You posted <strong><%= @company.job.length %></strong> jobs.<br><br>

                <%= link_to matches_path do %>
                    View All Matches  <i class="material-icons">link</i>
                  <% end %>

          </div>
        </div>
      </section>
      <% if @company.job.length != 0 %>
        <section class="posted-jobs">
          Here are your job listings:<br>
          <div class="board">
            <% @records.each do |job| %>
              <div class="listing">
              <div class="details">
                <div class="position-title">
                  <%= job.title %>
                </div>
                <span class="position-salary">$<%= job.offered_salary %></span> | <span
                  class="location"><%= job.country %></span><br>
                <p class="description"><%= job.description.truncate(100) %></p>
                <div class="skills">
                    <% job.skills.each do |skill| %>
                      <%= content_tag(:div, skill.name, class: "badge badge-pill badge-secondary") %>
                    <% end %>
                </div>
                <div class="actions">
                  <i class="material-icons">remove_red_eye</i>  <%= link_to "View Job", job_path(job) %> <% if @company && @company == job.company %>
                    | <%= link_to 'Edit', edit_job_path(job) %> or <%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %>
                  </div>
                  </div>
                <% end %>
              </div>
            <% end %>
          <br>
            <div class="clearfix"> </div>
          <%== pagy_bootstrap_nav(@pagy) %>
          </section>
        <% elsif %>
          <section class="posted-jobs">
            Hey! You haven't posted any jobs yet,
            <%= link_to new_job_path do %>
              post a new Job <i class="material-icons">add_circle_outline</i>
            </section>
          <% end %>
        <% end %>
      </div>
    </div>
  <% elsif user_candidate_signed_in? %>
    <% if @candidate %>
      <%# show candidate stuff. don't know what's relevant yet %>
      <div class="container candidate">
        <h2>Hey, <span class="highlight"><%= @candidate.given_name %></span>! </h2>
        <br>
        <section class="candidate-info">
          <div class="row">
            <div class="col-sm-7 profile">
              <div class="row">
                <div class="col-6">
                  <h3>Your Profile</h3>
                </div>
                <div class="col-6 text-right">
                  <%= link_to edit_candidate_path(@candidate) do %>
                    <i class="material-icons">edit</i>
                  <% end %></div>
              </div>
              <div class="row">
                <div class="col-8">
                  <strong>Given Name:</strong> <%= @candidate.given_name %> <br>
                  <strong>Family Name:</strong> <%= @candidate.family_name %> <br>
                  <strong>Years of experience:</strong> <%= @candidate.years_of_experience %> <br>
                  <strong>Expected salary:</strong> $<%= @candidate.expected_salary %> <br>
                </div>
                <div class="col-4 profile-image">
                  <%= image_tag current_user_candidate.gravatar_url %>
                </div>
              </div>
                  <strong>Bio:</strong> <%= @candidate.bio.truncate(150) %> <br>
              <strong>Skills:</strong> <% @candidate.skills.each do |skill| %>
                <%= content_tag(:div, skill.name, class: "badge badge-pill badge-available") %>
              <% end %>
              <% if @candidate.resume_url != nil %>
                <br><strong>Resume:</strong>
                <%= link_to "Link", @candidate.resume_url %>
              <% end %>
            </div>
            <div class="offset-sm-1 col-sm-4 stats pt-5">
              Your profile has been viewed <strong><%= @candidate.views %></strong> times.
              <br>
              <br>
              You expressed interest in <strong><%= @matches.length %></strong> jobs.<br><br>

                <%= link_to matches_path do %>
                    View All Matches  <i class="material-icons">link</i>
                  <% end %>

            </div>
          </div>
        </section>
        <% if @matches.length != 0 %>
          <section class="suggested-jobs">
            You've liked these jobs:<br>
            <div class="board">
              <% @matches.each do |m|%>
                <div class="listing">
                  <div class="position-title"><%= m.job.title %></div>
                  <span class="position-salary">$<%= m.job.offered_salary %></span> | <span
                class="location"><%= m.job.country %></span><br>
                  <p class="description"><%= m.job.description.truncate(100) %></p>
                  <div class="skills">
                    <% m.job.skills.each do |skill| %>
                      <% if m.candidate.skills.include? skill %>
                        <%= content_tag(:div, skill.name, class: "badge badge-pill badge-primary") %>
                      <% else %>
                        <%= content_tag(:span, skill.name, class: "badge badge-pill badge-secondary") %>
                      <% end %>
                    <% end %>
                  </div>
                  <div class="actions">
                    <i class="material-icons">remove_red_eye</i>  <%= link_to "View Job", job_path(m.job) %>
                    <% if @company && @company == job.company %>
                      | <%= link_to 'Edit', edit_job_path(job) %> or <%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
            <div class="clearfix"> </div>
            <%== pagy_bootstrap_nav(@pagy) %>
          </section>
        <% elsif %>
          <section class="suggested-jobs">
            You've not liked any jobs yet! <%= link_to jobs_path do %>View all Job Listings  <i class="material-icons">work_outline</i> <% end %>
          </section>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>