config/routes.rb
Rails.application.routes.draw do
  resources :room_messages
  resources :rooms
  get "matches/matches"
  resources :candidates
  resources :companies
  devise_for :user_candidates, path: "candidate", controllers: { sessions: "user_candidates/sessions", registrations: "user_candidates/registrations" }
  devise_for :user_companies, path: "company", controllers: { sessions: "user_companies/sessions", registrations: "user_companies/registrations" }
  resources :jobs
  resources :matches

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "dashboard#index"

  get "/companies/:id/jobs" => "jobs#filter_job_company"

  get "/dashboard" => "dashboard#show"

  get "/candidate/createprofile" => "candidates#edit"
  get "/candidate/:id/edit" => "candidates#edit"

  get "/jobs/:id/matches" => "matches#companiesmatch"

  get "/jobs/:jobs_id/matches" => "matches#companiesmatch"

  get "/matches" => "matches#candidatesmatch"

  get 'users/:user_id/challenges' => 'challenges#user_challenges', as: :user_challenges

  match "*path", to: "dashboard#index", via: :all
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user_company
  has_many :job

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user_company!, :except => [:show, :index]

  def index
    redirect_to dashboard_path
  end

  def show
    @company = Company.find(params[:id])
    if current_user_company
      if current_user_company.company == @company
      else
        @company.views += 1
        @company.save
      end
    else
      @company.views += 1
      @company.save
    end
  end

  def new
    if current_user_company.company #company exists
      redirect_to "/"
    end
  end

  def edit
    cookies.signed[:email] = current_user_company.email
    @company = Company.find(params[:id])
  end

  def create
    @company = Company.new(company_params)
    if current_user_company.company
      redirect_to "/" # company exists. disallow creation
    else
      @company.user_company = current_user_company
      @company.save
      redirect_to @company # redirect to root path for now, may want to redirect to jobs
    end
  end

  def update
    @company = Company.find(params[:id])
    if params["company"]["avatar"] != nil
      result = Cloudinary::Uploader.upload(params["company"]["avatar"])
      @company.avatar_url = result["url"]
      @company.update(company_params)
    else
      @company.update(company_params)
    end
    redirect_to "/dashboard/"
    # redirect_to '/companies/' + params[:id]
  end

  def destroy
  end

  private

  def company_params
    params.require(:company).permit(:name, :industry, :size)
  end
end

app/views/companies/edit.html.erb
<%= title "Linkdr | Edit Profile" %>


<div class="container candidate">
  <h2>Edit your profile</h2>
  <br>
  <div class="form">
    <%= form_with scope: :company, model: @company, local: true do |form| %>
      <div class="row">
        <div class="col-sm-12">
          <div class="field">
            <%= form.label :company_name %><br>
            <%= form.text_field :name %>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="field">
            <%= form.label :industry %><br>
            <%= form.text_field :industry %>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="field">
            <% @company_size = ["Small, 0-10 employees", "Medium, 10-50 employees",
              "Large 50-200 employees", "Multinational 200+ employees"] %>
            <%= form.label :company_Size %><br>
            <%= form.collection_select :size, @company_size, :to_s, :to_s, {:include_blank => false}, {:class => 'form-control form-control-lg'} %>
          </div>
        </div>
        <div class="col-sm-12">
          <div class="field">
            <%= form.label :avatar %><br>
            <%= form.file_field :avatar, accept: 'image/png,image/jpg,image/jpeg,image/gif' %>
          </div>
        </div>
        <div class="col-sm-12">
          <div class="actions row">
            <div class="col-sm-6">
              <%= link_to 'Back', url_for(:back) %>
            </div>
            <div class="col-sm-6 text-right">
              <%= form.submit %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/companies/new.html.erb
<%= form_with scope: :company, url: new_company_path, local: true do |form| %>
  <p>
    <%= form.label :company_name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :industry %><br>
    <%= form.text_area :industry %>
  </p>

  <p>
    <%= form.label :company_Size %><br>
    <%= form.text_area :size %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/companies/show.html.erb
<h1><%= @company.name %></h1>
<div class="h1-after company">&nbsp;</div>

<div class="container companies">
<p>Company name: <%= @company.name %></p>
<p>Company size: <%= @company.size %></p>
<p>Industry: <%= @company.industry %></p>
<section class="jobs">
    <h2>Your job listings</h2>
    <!-- insert listings similar to candidate's suggested job listings -->
</section>
</div>