config/routes.rb
Rails.application.routes.draw do
  resources :room_messages
  resources :rooms
  get "matches/matches"
  resources :candidates
  resources :companies
  devise_for :user_candidates, path: "candidate", controllers: { sessions: "user_candidates/sessions", registrations: "user_candidates/registrations" }
  devise_for :user_companies, path: "company", controllers: { sessions: "user_companies/sessions", registrations: "user_companies/registrations" }
  resources :jobs
  resources :matches

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "dashboard#index"

  get "/companies/:id/jobs" => "jobs#filter_job_company"

  get "/dashboard" => "dashboard#show"

  get "/candidate/createprofile" => "candidates#edit"
  get "/candidate/:id/edit" => "candidates#edit"

  get "/jobs/:id/matches" => "matches#companiesmatch"

  get "/jobs/:jobs_id/matches" => "matches#companiesmatch"

  get "/matches" => "matches#candidatesmatch"

  get 'users/:user_id/challenges' => 'challenges#user_challenges', as: :user_challenges

  match "*path", to: "dashboard#index", via: :all
end

app/models/room.rb
class Room < ApplicationRecord
belongs_to :match
has_many :room_messages, dependent: :destroy,
                         inverse_of: :room


end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # Loads:
  # @rooms = all rooms
  # @room = current room when applicable
  

  def index
    @rooms = Room.all
    redirect_to dashboard_path
  end

  def new
    @room = Room.new
  end

  
def show
  @room = Room.find(params[:id])
  if user_company_signed_in?
  @company = current_user_company.company
  else 
  @candidate = current_user_candidate.candidate
  end

  @match = Match.find(params[:id])

  # If you are logged in as a company or a candidate 
  # Check if you should be in the room 
  if @company 
    if @match.job.company.user_company.email != cookies.signed['email']
      redirect_to dashboard_path
    end
  elsif @candidate
    if @match.candidate.user_candidate.email != cookies.signed['email']
      redirect_to dashboard_path
    end
  end

  @room_messages = RoomMessage.where( room_id:params[:id])
  @room_message = RoomMessage.new room: @room
  
end


  def create
    puts permitted_parameters
    @room = Room.new(permitted_parameters)

    if @room.save
      flash[:success] = "Room #{@room.name} was created successfully"
      redirect_to rooms_path
    else
      render plain: "failed"
    end
  end

  def edit
  end

  def update
    if @room.update_attributes(permitted_parameters)
      flash[:success] = "Room #{@room.name} was updated successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  protected


  def load_entities
    @rooms = Room.all
    @room = Room.find(params[:id]) if params[:id]
  end

  def permitted_parameters
    params.require(:room).permit(:name)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<%= form_for @room do |form| %>
  <%= form.text_field :name %>
  <%= form.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/rooms/index.html.erb
<h1>Rooms index</h1>

<div class="row">
  <div class="col-12 col-md-3">
    <div class="mb-3">
      <%= link_to new_room_path, class: "btn btn-primary" do %>
        Create a room
      <% end %>
    </div>

    <% if @rooms.present? %>
      <nav class="nav flex-column">
        <% @rooms.each do |room| %>
          <%= link_to room.name, room_path(room), class: "nav-link room-nav-link" %>
        <% end %>
      </nav>
    <% else %>
      <div class="text-muted">
        The are no rooms
      </div>
    <% end %>
  </div>

  <div class="col">
    <div class="alert alert-primary">
      <h4 class="alert-heading">
        Welcome to the RailsChatTutorial!
      </h4>

      <p>
        We need to talk.
      </p>

      <hr />

      <p>
        You can create or join a room from the sidebar.
      </p>
    </div>
</div>

app/views/rooms/new.html.erb
<%= form_for @room do |form| %>
  <%= form.text_field :name %>
  <%= form.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/rooms/show.html.erb
<%= title "Linkdr | Chat" %>
<h1>Chat</h1>
<div class="h1-after">&nbsp;</div>

<div class="container">
  <p class="text-center"><span class="font-weight-bold"><%= @room.match.candidate.given_name %> <%= @room.match.candidate.family_name %></span> is applying for the role of
  <span class="font-weight-bold"><%= @room.match.job.title %></span> at
  <span class="font-weight-bold"><%= @room.match.job.company.name %></span>
  </p>

  <div class="col">
    <div class="chat" data-channel-subscribe="room" data-room-id="<%= @room.id %>">
      <% @room_messages.each do |room_message| %>
        <div class="chat-message-container">
          <div class="row no-gutters">
            <div class="col-auto">
               <span class="user-name"><%= room_message.name %>:</span>
            </div>

            <div class="col">
              <div class="message-content">
                <p class="mb-1 px-3">
                  <%= room_message.message %>
                </p>

                <div class="text-right">
                  <small>
                  <em class="timestamp">
                    <%= time_ago_in_words(room_message.updated_at)%> ago
                    </em>
                  </small>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <%= simple_form_for @room_message,  remote: true do |form| %>
      <div id="the-input-box" class="input-group">
        <%= form.input :message, as: :string,
                                 wrapper: false,
                                 label: false,
                                 input_html: {
                                   class: 'chat-input col-9',
                                   placeholder: 'Type a message...',
                                   autocomplete: 'off',
                                   autofocus: 'true'
                                 } %>
        <div class="input-group-append col-3">
          <%= form.submit "Send", class: 'btn btn-primary chat-input' %>
        </div>
      </div>

      <%= form.input :room_id, as: :hidden %>
    <% end %>
  </div>
</div>

</div>

<div class="d-none" data-role="message-template">
  <div class="chat-message-container">
    <div class="row no-gutters">
      <div class="col-auto text-center">
        <span data-role="user-name"></span>:
      </div>


      <div class="col">
        <div class="message-content">
          <p class="mb-1 px-3" data-role="message-text">
          </p>

          <div class="text-right">
            <small data-role="message-date">
            </small>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>