config/routes.rb
Rails.application.routes.draw do
  resources :room_messages
  resources :rooms
  get "matches/matches"
  resources :candidates
  resources :companies
  devise_for :user_candidates, path: "candidate", controllers: { sessions: "user_candidates/sessions", registrations: "user_candidates/registrations" }
  devise_for :user_companies, path: "company", controllers: { sessions: "user_companies/sessions", registrations: "user_companies/registrations" }
  resources :jobs
  resources :matches

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "dashboard#index"

  get "/companies/:id/jobs" => "jobs#filter_job_company"

  get "/dashboard" => "dashboard#show"

  get "/candidate/createprofile" => "candidates#edit"
  get "/candidate/:id/edit" => "candidates#edit"

  get "/jobs/:id/matches" => "matches#companiesmatch"

  get "/jobs/:jobs_id/matches" => "matches#companiesmatch"

  get "/matches" => "matches#candidatesmatch"

  get 'users/:user_id/challenges' => 'challenges#user_challenges', as: :user_challenges

  match "*path", to: "dashboard#index", via: :all
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? content_for(:title) : "Linkdr" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body class="<%= 'home' if @home %>">
    <div class="container">
      <% if @home %>
        <nav class="navbar">
          <% if user_candidate_signed_in? || user_company_signed_in? %>
            they are signed in
          <% elsif %>
            <%= link_to "/candidate/sign_in" do %>
              candidate log in
            <% end %>
            <%= link_to "/company/sign_in" do %>
              company log in
            <% end %>
          <% end %>
        </nav>
      <% elsif %>
        <nav class="navbar">
          <%= link_to "/" do %>
            <%= image_tag('/logo.png') %>
          <% end %>
          
          <% if user_company_signed_in? %>
            <div class="text-right d-flex">
            <span class="badge pill badge-user"><%= @company.name %></span> &nbsp; &nbsp;
              <div class="dropdown show">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons header-icon">supervisor_account</i> <em>companies</em>
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <%= link_to new_job_path, class: "dropdown-item" do %>
                    Post A New Job <i class="material-icons">add_circle_outline</i>
                  <% end %>
                  <%= link_to jobs_path, class: "dropdown-item" do %>
                    Job Listings  <i class="material-icons">work_outline</i>
                  <% end %>
                <%= link_to matches_path, class: "dropdown-item" do %>
                    Matches  <i class="material-icons">link</i>
                  <% end %>
                  <%= link_to 'Account', dashboard_path, class: "dropdown-item" %>
                  <div class="dropdown-divider"></div>
                  <%= link_to 'Log Out', destroy_user_company_session_url, method: :delete, class: "dropdown-item" %>
                </div>
              </div>
            </div>
          <% elsif user_candidate_signed_in? %>
            <div class="text-right d-flex">
            <span class="badge pill badge-user"><%= @candidate.given_name %></span> &nbsp; &nbsp;
              <div class="dropdown show">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons header-icon">face</i> <em>candidates</em>
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink1">
                <%= link_to jobs_path, class: "dropdown-item" do %>
                    Job Listings  <i class="material-icons">work_outline</i>
                  <% end %>
                <%= link_to matches_path, class: "dropdown-item" do %>
                    Matches  <i class="material-icons">link</i>
                  <% end %>
                  <%= link_to 'Account', dashboard_path, class: "dropdown-item" %>
                  <div class="dropdown-divider"></div>
                  <%= link_to 'Log Out', destroy_user_candidate_session_url, method: :delete, class: "dropdown-item" %>
                </div>
              </div>
            <% end %>
          </div>
        </nav>
      <% end %>
    </div>
    <%= yield %>
    <% if @home %>
    <% elsif %>
      <footer>
        <div class="container">
          <div class="row d-flex">
            <div class="col-sm-4">
              <h3>About</h3>
              &copy; <strong>SBRWZ</strong> 2020.<br>
              All Rights Reserved.</div>
            <div class="col-sm-4">
              <h3>Links</h3>
              <%= link_to "/company/sign_in" do %>Company<% end %> | <%= link_to "/candidate/sign_in" do %>Candidate<% end %></div>
            <div class="col-sm-4">
              <h3>Contact</h3>
              Please do not contact us.</div>
          </div>
        </div>
      </footer>
    <% end %>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
  </body>
</html>